/**
 * This code defines a Redux slice for handling authentication-related state.
 * Also stores user details
 */

import { createSlice } from "@reduxjs/toolkit";
const profileSlice = createSlice({
  name: "profile",
  initialState: {
    isLoggedIn: false // Holds user details like name, email, etc.
  },
  reducers: {
    // Action for setting the countdown start flag
    setCountdownStart(state, action) {
      state.isLoggedIn = action.payload;
    }
  }
});

// Extract the actions created by the authSlice
export const {
  setCountdownStart
} = profileSlice.actions;

// Export the reducer function generated by the authSlice
export default profileSlice.reducer;